apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: neuron
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 1h
    consolidationPolicy: WhenEmpty
  template:
    metadata: {}
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: trainium-trn1
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values:
            - inf
            - trn          
      terminationGracePeriod: 24h0m0s