apiVersion: apps/v1
kind: Deployment
metadata:
  name: decision-handler
  namespace: moderation-system
  labels:
    app.kubernetes.io/name: decision-handler
    app.kubernetes.io/component: decision
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: decision-handler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: decision-handler
        app.kubernetes.io/component: decision
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8003"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: moderation-service-account
      # Deploy to your custom nodepool
      nodeSelector:
        owner: "data-engineer"
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "custom-workload"
        effect: "NoSchedule"
      containers:
      - name: decision-handler
        image: your-registry/decision-handler:latest  # Replace with your image
        ports:
        - containerPort: 8003
          name: http
        env:
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-service:5432/$(DATABASE_NAME)"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: moderation-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: moderation-secrets
              key: postgres-password
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: moderation-config
              key: database-name
        - name: DATABASE_POOL_SIZE
          valueFrom:
            configMapKeyRef:
              name: moderation-config
              key: database-pool-size
        - name: DATABASE_MAX_OVERFLOW
          valueFrom:
            configMapKeyRef:
              name: moderation-config
              key: database-max-overflow
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: moderation-config
              key: log-level
        - name: NOTIFICATION_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: moderation-secrets
              key: notification-webhook
              optional: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
