apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: moderation-system
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: moderation-system
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
spec:
  selector:
    app.kubernetes.io/name: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-server-service
  namespace: moderation-system
  labels:
    app.kubernetes.io/name: mcp-server
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: mcp-server
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: lightweight-filter-service
  namespace: moderation-system
  labels:
    app.kubernetes.io/name: lightweight-filter
    app.kubernetes.io/component: filter
spec:
  selector:
    app.kubernetes.io/name: lightweight-filter
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: chat-simulator-service
  namespace: moderation-system
  labels:
    app.kubernetes.io/name: chat-simulator
    app.kubernetes.io/component: simulator
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app.kubernetes.io/name: chat-simulator
  ports:
  - name: http
    port: 8002
    targetPort: 8002
    protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: decision-handler-service
  namespace: moderation-system
  labels:
    app.kubernetes.io/name: decision-handler
    app.kubernetes.io/component: decision
spec:
  selector:
    app.kubernetes.io/name: decision-handler
  ports:
  - name: http
    port: 8003
    targetPort: 8003
    protocol: TCP
  type: ClusterIP
